# Generated by Django 3.2.3 on 2021-08-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='statring_bid',
            new_name='price',
        ),
    ]
