# Generated by Django 3.2.3 on 2021-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_statring_bid_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='bids',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='comment',
            new_name='comments',
        ),
    ]
