# Generated by Django 3.2.3 on 2021-09-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Watchlist',
        ),
    ]
